### ISSUE TITLE
[24.0] Mandrel builds fail with JDK 22.0.2-ea

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#716]
## Description

Mandrel 24.0 builds have started failing with `22.0.2-ea` (masked as `22.0.1-beta+36-202404131209`, since Oracle doesn't provide a tree with 22.0.2 ea sources) due to the backport of https://bugs.openjdk.org/browse/JDK-8324646 to JDK 22 (https://bugs.openjdk.org/browse/JDK-8329554)

Failures look like this:

```
Failed generating 'quarkus-integration-test-resteasy-jackson-999-SNAPSHOT-runner' after 29.1s.

The build process encountered an unexpected error:

com.oracle.svm.core.util.VMError$HostedError: InternalFeature defined by com.oracle.svm.hosted.SecurityServicesFeature unexpectedly failed with a(n) com.oracle.svm.util.ReflectionUtil$ReflectionUtilError
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:86)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.handleFeatureError(FeatureHandler.java:293)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:95)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:784)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:571)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:537)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:526)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:701)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:140)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:95)
Caused by: com.oracle.svm.util.ReflectionUtil$ReflectionUtilError: java.lang.NoSuchFieldException: constructorParameterClassName
	at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupField(ReflectionUtil.java:161)
	at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupField(ReflectionUtil.java:133)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.SecurityServicesFeature.getConstructorParameterClassAccessor(SecurityServicesFeature.java:662)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.SecurityServicesFeature.registerServiceReachabilityHandlers(SecurityServicesFeature.java:527)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.SecurityServicesFeature.beforeAnalysis(SecurityServicesFeature.java:332)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:784)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:93)
	... 7 more
Caused by: java.lang.NoSuchFieldException: constructorParameterClassName
	at java.base/java.lang.Class.getDeclaredField(Class.java:2792)
	at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupField(ReflectionUtil.java:140)
	... 13 more
```

See:
https://github.com/graalvm/mandrel/actions/runs/8747051267/job/24004916272#step:8:519
and
https://github.com/graalvm/mandrel/actions/runs/8747051267/job/24005368747#step:13:2700

**Comment by jerboaa** [comment]
Yes, but this is the wrong milestone. We need this fixed for Mandrel 24.0.2 which corresponds to the 22.0.2 update. The current JDK 22 update is `22.0.1` which is why we don't see it in the current release.

**Comment by jerboaa** [comment]
Fixed with: https://github.com/graalvm/mandrel/pull/722 I'm going to close this issue, once we see CI passing again.

**Comment by zakkak** [comment]
Mandrel builds no longer fail, but the CI is still not passing due to https://github.com/graalvm/mandrel/issues/731
